services:

  db:
    image: mysql:latest
    container_name: docker_sf5_mysql
    volumes: 
      - db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  adminer:
    image: adminer:latest
    container_name: docker_sf5_adminer
    depends_on:
     - db
    environment:
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    ports: 
      - "${ADMINER_PORT}:8080"
    restart: always

  maildev:
    image: maildev/maildev
    container_name: docker_sf5_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
        - "${MAILDEV_PORT}:80"
    restart: always

  php:
    image: webdevops/php-apache-dev:7.4
    container_name: docker_sf5_www
    depends_on:
     - db
    ports:
     - "${HTTP_PORT}:80"
     - "${SSL_PORT}:443"
    volumes:
      - ./app:/app:cached
      - .bashrc:/root/.bashrc
      - var:/app/var
      - vendor:/app/vendor
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    restart: always

volumes: 
  db_data:
  var:
  vendor:
